name: pomodoro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

flutter:

  uses-material-design: true
